### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by fantasyRqg** [IANW-Projects/MatCL#19]
```Building with 'Xcode Clang++'.
Error using mex
/Users/rqg/MatlabProjects/MatCL/src/cl_get_devices.cpp:12:10: fatal error: 'CL/cl2.hpp' file not found
#include <CL/cl2.hpp>
         ^~~~~~~~~~~~
1 error generated.


Error in compile_lx (line 8)
mex -g COMPFLAGS='$COMPFLAGS -std=c++11 -O2' '-LC /usr/lib/x86_64-linux-gnu' -lOpenCL src/cl_get_devices.cpp src/ocl_dev_mgr.cpp``` 





what should I do ?

**Comment by ranocha** [comment]
You need to install the OpenCL headers, in particular `cl2.hpp`. On Debian based systems, you can simply install the package `opencl-headers`. Does this help?

**Comment by ranocha** [comment]
Having a look at the history of your post, it seems that you are not using Linux but Mac OS X. Up to now, we didn't have good access to Apple systems so that we could'n test `MatCL` there. You might want to have a look at https://rageandqq.github.io/blog/2018/03/09/opencl-mac-cpp.html in order to install OpenCL on Apple systems.

**Comment by fantasyRqg** [comment]
OK, thanks

**Comment by ranocha** [comment]
Could you please check whether the new build script `compile_mac.m` in #20 works for you, @fantasyRqg?

**Comment by ranocha** [comment]
We have merged the build script for Apple Mac OS X developed in #20 into master. Could you please report whether there are any problems with this new build script, @fantasyRqg?
